project:
  type: book

lightbox: auto

book:
  title: "R入門"
  author: "xjorv"
  version: 0.1.0
  search: true
  date: "2023/9/29"
  license: "CC BY-NC-SA"
  
  page-navigation: true
  
  page-footer:
    right: |
      <a href="https://quarto.org/">Quarto</a>を用いてこの本を作成しました

  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - part: "Rプログラミングの基礎"
      chapters: 
      - chapter1.qmd
      - chapter2.qmd
      - chapter3.qmd
      - chapter4.qmd
      - chapter5.qmd
      - chapter6.qmd
      - chapter7.qmd
      - chapter8.qmd
      - chapter9.qmd
      - chapter10.qmd
      - chapter11.qmd
      - chapter12.qmd
      - chapter13.qmd
      - chapter14.qmd
    - part: "Rでのデータの取り扱い"
      chapters: 
      - chapter15.qmd
      - chapter16.qmd
      - chapter17.qmd
      - chapter18.qmd
      - chapter19.qmd
    - part: "Rでのグラフ作成"
      chapters:
      - chapter20.qmd
      - chapter21.qmd
      - chapter22.qmd
      - chapter23.qmd
    - part: "統計解析の基礎"
      chapters:     
      - chapter24.qmd
      - chapter25.qmd
      - chapter26.qmd
      - chapter27.qmd
      - chapter28.qmd
      - chapter29.qmd
      - chapter30.qmd
    - part: "アドバンスな手法"
      chapters:
      - chapter31.qmd
      - chapter32.qmd
      - chapter33.qmd
      - chapter34.qmd
      - chapter35.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: united
      dark: cyborg
    toc: true
    toc-depth: 4
    toc-expand: 2
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

editor: source
