project:
  type: book

lightbox: auto

# lang: ja

book:
  title: "R入門"
  author: "xjorv"
  version: 0.4.4.5
  search: 
    limit: 100
  date: "2023/9/29"
  license: "CC BY-NC-SA"
  sharing: [twitter, facebook]
  favicon: favicon.ico
  cover-image: ./image/favicon_small.png
  site-url: https://sb8001at-oss.github.io/Rnyuumon.io/
  
  google-analytics: "G-M8N5QERSYQ"
  
  page-navigation: true
  
  page-footer:
    right:
      - text: <a href="https://quarto.org/">Quarto</a>を用いてこの本を作成しました
    left:
      - text: © xjorv, 2025

  sidebar:
    style: docked
    background: light
    collapse: true
    tools: 
      - icon: github
        menu: 
          - text: ソースコード
            href: https://github.com/sb8001at-oss/Rnyuumon
          - text: 修正・ご意見はこちらへ
            href: https://github.com/sb8001at-oss/Rnyuumon.io/discussions
#    logo: ./image/qrcode.png
    
  chapters:
    - index.qmd
    - part: "Rプログラミングの基礎"
      chapters: 
      - chapter1.qmd
      - chapter2.qmd
      - chapter3.qmd
      - chapter4.qmd
      - chapter5.qmd
      - chapter6.qmd
      - chapter7.qmd
      - chapter8.qmd
      - chapter9.qmd
      - chapter10.qmd
      - chapter11.qmd
      - chapter12.qmd
      - chapter13.qmd
      - chapter14.qmd
      - chapter15.qmd
      - chapter16.qmd
      - chapter17.qmd
      - chapter18.qmd
    - part: "Rでのデータの取り扱い"
      chapters: 
      - chapter19.qmd
      - chapter20.qmd
      - chapter21.qmd
      - chapter22.qmd
      - chapter23.qmd
    - part: "Rでのグラフ作成"
      chapters:
      - chapter24.qmd
      - chapter25.qmd
      - chapter26.qmd
      - chapter27.qmd
    - part: "統計解析の基礎"
      chapters:     
      - chapter28.qmd
      - chapter29.qmd
      - chapter30.qmd
      - chapter31.qmd
      - chapter32.qmd
      - chapter33.qmd
      - chapter34.qmd
    - part: "R markdownとQuarto"
      chapters:
      - chapter35.qmd
      - chapter36.qmd
      - chapter37.qmd
      - chapter38.qmd
      - chapter39.qmd
      - chapter40.qmd
      - chapter41.qmd
      - chapter42.qmd
      - chapter43.qmd
    - part: "アドバンスドな手法"
      chapters:
      - chapter44.qmd
      - chapter45.qmd
      - chapter46.qmd
      - chapter47.qmd
      - chapter48.qmd
      - chapter49.qmd
      - chapter50.qmd
      - chapter51.qmd
    - part: "Tips"
      chapters:
      - Tips_ParallelComputing.qmd
      - Tips_systems.qmd
      - Tips_S3class.qmd
      - Tips_S4class.qmd
      - Tips_R6class.qmd
      - Tips_S7class.qmd
      - Tips_shinylive.qmd
      - Tips_mall.qmd

    - summary.qmd
    - references.qmd

bibliography: references.bib

website:
  back-to-top-navigation: true
  site-url: 'https://sb8001at-oss.github.io/Rnyuumon.io'
  site-path: '/'
#  llms-txt: true

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    theme: 
      light: united
      dark: cyborg
    toc: true
    toc-depth: 4
    toc-expand: 2
    code-tools: true
    code-link: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

execute:
  freeze: false
#  cache: true

editor: source